### ISSUE TITLE
Ability to pick-up and target place ArmorStand.

### ISSUE THREAD

**Issue by mibby** [RypoFalem/ArmorStandEditor#6]
Would it be possible to allow for an armorstand to be picked up and target placed? Similarly to how this plugin carries an armorstand when summoning one using their tools. Similarly to this plugin. https://www.spigotmc.org/resources/armor-stand-tools.2237/

**Comment by RypoFalem** [comment]
There is no pickup and put down feature. There is, however, a copy/paste and use can effectively use that for the same purpose. In creative it will paste everything to another armorstand. In survival, it will paste everything except equipment (because it would allow duplicating).

**Comment by mibby** [comment]
It wouldn't be possible to implement something like that plugin? Which does have a direct place / put down feature.

**Comment by RypoFalem** [comment]
It would be possible but right now I think it would go against the spirit of the plugin: editing the attributes of armorstands. This philosophy keeps the plugin simple and focused rather than complex and feature bloated.

You can already move the entire armorstand using the Placement function which is useful for short distances and you can already copy/paste to move it long distances or duplicate it many times. The potential for benefit is realitivly low since there are already multiple ways to accomplish the same goal. The potential for bloat is there because it's another thing to code, maintain and clutter the menu.

I haven't had a long time to consider this feature suggestion. My answer isn't "no" but rather "I will have to weigh the costs and benefits".

**Comment by RoboMWM** [comment]
I also vote against this "feature" - only "benefit" I see is providing a visual that users on mibby's server are familiar with.

**Comment by mibby** [comment]
Alright, no biggie. I actually don't use that plugin, just something I found when searching for armor stand plugins and thought was neat to make transferring armor stands more visual with a fine level of control.

**Comment by RoboMWM** [comment]
Oh ok, my apologies. But yea, other factors include having to constantly update armor stand position on PlayerMoveEvent which introduces the possibility of lag
